print("Give me a noun")
noun1 = input()
print("Give me another noun")
noun2 = input()
print("Give me a verb")
verb1 = input()
print("Give me another verb")
verb2 = input()
print("Give me one last verb")
verb3 = input()
print("Give me an adjective")
adj = input()
print("There once was a " + noun1 + " that existed. He loved " +verb1+ "ing with a " + adj + " " + noun2 + ". They liked to " + verb1 +", " + verb2 + ", and " + verb3 + " all day. FIN")
